### PR TITLE
Use latest beautifulsoup

### LINKED ISSUE #17: AttributeError: module 'collections' has no attribute 'Callable'
When I try to run DataCrawler.py on my recently downloaded 23andme genome, I get this error.

```
Traceback (most recent call last):
  File "/home/danielmcnally/github/OSGenome/SNPedia/DataCrawler.py", line 168, in <module>
    dfCrawl = SNPCrawl(rsids=rsid)
  File "/home/danielmcnally/github/OSGenome/SNPedia/DataCrawler.py", line 35, in __init__
    self.initcrawl(rsids)
  File "/home/danielmcnally/github/OSGenome/SNPedia/DataCrawler.py", line 43, in initcrawl
    self.grabTable(rsid)
  File "/home/danielmcnally/github/OSGenome/SNPedia/DataCrawler.py", line 63, in grabTable
    bs = BeautifulSoup(html, "html.parser")
  File "/home/danielmcnally/github/OSGenome/venv/lib/python3.10/site-packages/bs4/__init__.py", line 228, in __init__
    self._feed()
  File "/home/danielmcnally/github/OSGenome/venv/lib/python3.10/site-packages/bs4/__init__.py", line 289, in _feed
    self.builder.feed(self.markup)
  File "/home/danielmcnally/github/OSGenome/venv/lib/python3.10/site-packages/bs4/builder/_htmlparser.py", line 167, in feed
    parser.feed(markup)
  File "/usr/lib/python3.10/html/parser.py", line 110, in feed
    self.goahead(0)
  File "/usr/lib/python3.10/html/parser.py", line 178, in goahead
    k = self.parse_html_declaration(i)
  File "/usr/lib/python3.10/html/parser.py", line 269, in parse_html_declaration
    self.handle_decl(rawdata[i+2:gtpos])
  File "/home/danielmcnally/github/OSGenome/venv/lib/python3.10/site-packages/bs4/builder/_htmlparser.py", line 112, in handle_decl
    self.soup.endData(Doctype)
  File "/home/danielmcnally/github/OSGenome/venv/lib/python3.10/site-packages/bs4/__init__.py", line 365, in endData
    self.object_was_parsed(o)
  File "/home/danielmcnally/github/OSGenome/venv/lib/python3.10/site-packages/bs4/__init__.py", line 370, in object_was_parsed
    previous_element = most_recent_element or self._most_recent_element
  File "/home/danielmcnally/github/OSGenome/venv/lib/python3.10/site-packages/bs4/element.py", line 1040, in __getattr__
    return self.find(tag)
  File "/home/danielmcnally/github/OSGenome/venv/lib/python3.10/site-packages/bs4/element.py", line 1278, in find
    l = self.find_all(name, attrs, recursive, text, 1, **kwargs)
  File "/home/danielmcnally/github/OSGenome/venv/lib/python3.10/site-packages/bs4/element.py", line 1299, in find_all
    return self._find_all(name, attrs, text, limit, generator, **kwargs)
  File "/home/danielmcnally/github/OSGenome/venv/lib/python3.10/site-packages/bs4/element.py", line 528, in _find_all
    strainer = SoupStrainer(name, attrs, text, **kwargs)
  File "/home/danielmcnally/github/OSGenome/venv/lib/python3.10/site-packages/bs4/element.py", line 1596, in __init__
    self.text = self._normalize_search_value(text)
  File "/home/danielmcnally/github/OSGenome/venv/lib/python3.10/site-packages/bs4/element.py", line 1601, in _normalize_search_value
    if (isinstance(value, str) or isinstance(value, collections.Callable) or hasattr(value, 'match')
AttributeError: module 'collections' has no attribute 'Callable'
```

### PR DESCRIPTION
**Pull request by sangaman**
This enables support for python 3.10, and should still work with python 3.6+ according to the BeautifulSoup website.

Fixes #17

### CODE REVIEW

**Comment by mentatpsi** [comment]
No PRs are accepted on this branch given nature of code. I've implemented your change.

**Comment by sangaman** [comment]
> No PRs are accepted on this branch given nature of code. I've implemented your change.

Just curious but what do you mean by this? What nature?

**Comment by mentatpsi** [comment]
The software links up your genetics locally. There are privacy concerns with SNP data. I personally designed this software so that users can feel safe about their genetic data. I like to keep the code closed off so users don't need to worry about the code origins. Sorry I couldn't give you a PR request for your work on this ticket. I appreciate your work though debugging this issue.

**Comment by mentatpsi** [comment]
I've given you credit in this issue ticket:
https://github.com/mentatpsi/OSGenome/issues/17

**Comment by mentatpsi** [comment]
Also provided credit on the commit itself:
https://github.com/mentatpsi/OSGenome/commit/cf798c12271c980bf029e84d3c2c104cf7d1acd7

**Comment by mentatpsi** [comment]
Hope this is adequate for your work on this issue.

**Comment by mentatpsi** [comment]
Decided to merge it. I realized your work, research, and time will get lost if it's not merged. Thanks again.

**Comment by sangaman** [comment]
> Decided to merge it. I realized your work, research, and time will get lost if it's not merged. Thanks again.

Thanks! I wasn't offended or anything but I appreciate the credit. IMO, plenty of open source projects that handle critical or sensitive data accept PRs, which is fine as long as they're well reviewed and well understood.

Thanks for putting this project together, it was fun and interesting to use.
